title: jneines
description: my page
author: Jens Nie
remote_theme: epidrome/cover-card@main
twitter: jneines


social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: twitter
    url-pattern: twitter.com/__USERNAME__
